<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Imposter.Game.Domain/Imposter.Game.Domain.csproj" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
</Project>
